# Generated by Django 5.1.2 on 2024-10-23 12:02

import payments.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('humo', 'Humo'), ('uzcard', 'Uzcard'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=10)),
                ('number', models.CharField(max_length=16)),
                ('deadline', models.CharField(max_length=5, validators=[payments.validators.deadline_validator])),
                ('bank', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
